/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StaffIndexImport } from './routes/staff/index'
import { Route as StaffCreateImport } from './routes/staff/create'
import { Route as MasterSchoolImport } from './routes/master/school'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgetPasswordImport } from './routes/auth/forget-password'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StaffIndexRoute = StaffIndexImport.update({
  path: '/staff/',
  getParentRoute: () => rootRoute,
} as any)

const StaffCreateRoute = StaffCreateImport.update({
  path: '/staff/create',
  getParentRoute: () => rootRoute,
} as any)

const MasterSchoolRoute = MasterSchoolImport.update({
  path: '/master/school',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgetPasswordRoute = AuthForgetPasswordImport.update({
  path: '/auth/forget-password',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/forget-password': {
      preLoaderRoute: typeof AuthForgetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/master/school': {
      preLoaderRoute: typeof MasterSchoolImport
      parentRoute: typeof rootRoute
    }
    '/staff/create': {
      preLoaderRoute: typeof StaffCreateImport
      parentRoute: typeof rootRoute
    }
    '/staff/': {
      preLoaderRoute: typeof StaffIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthForgetPasswordRoute,
  AuthLoginRoute,
  AuthRegisterRoute,
  MasterSchoolRoute,
  StaffCreateRoute,
  StaffIndexRoute,
])

/* prettier-ignore-end */
