/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as IndexImport } from './pages/index'
import { Route as StaffIndexImport } from './pages/staff/index'
import { Route as SiswaIndexImport } from './pages/siswa/index'
import { Route as SekolahIndexImport } from './pages/sekolah/index'
import { Route as PsbIndexImport } from './pages/psb/index'
import { Route as PortalIndexImport } from './pages/portal/index'
import { Route as InformasiIndexImport } from './pages/informasi/index'
import { Route as DashboardIndexImport } from './pages/dashboard/index'
import { Route as CbtIndexImport } from './pages/cbt/index'
import { Route as AkademikIndexImport } from './pages/akademik/index'
import { Route as AgendaIndexImport } from './pages/agenda/index'
import { Route as StaffStaffEditImport } from './pages/staff/staff-edit'
import { Route as StaffStaffCreateImport } from './pages/staff/staff-create'
import { Route as SiswaSiswaDetailImport } from './pages/siswa/siswa-detail'
import { Route as PsbPsbDetailImport } from './pages/psb/psb-detail'
import { Route as CbtCbtSoalFormImport } from './pages/cbt/cbt-soal-form'
import { Route as authLoginImport } from './pages/(auth)/login'
import { Route as PenggunaProfilIndexImport } from './pages/pengguna/profil/index'
import { Route as PenggunapenggunaIndexImport } from './pages/pengguna/(pengguna)/index'
import { Route as PenggajianProfilGajiStaffIndexImport } from './pages/penggajian/profil-gaji-staff/index'
import { Route as PenggajianProfilGajiGuruIndexImport } from './pages/penggajian/profil-gaji-guru/index'
import { Route as PenggajianpenggajianIndexImport } from './pages/penggajian/(penggajian)/index'
import { Route as PelanggaranPointPelanggaranIndexImport } from './pages/pelanggaran/point-pelanggaran/index'
import { Route as PelanggaranPelanggaranSiswaIndexImport } from './pages/pelanggaran/pelanggaran-siswa/index'
import { Route as PelanggaranJenisPelanggaranIndexImport } from './pages/pelanggaran/jenis-pelanggaran/index'
import { Route as KeuanganRekapitulasiIndexImport } from './pages/keuangan/rekapitulasi/index'
import { Route as KeuanganPengeluaranIndexImport } from './pages/keuangan/pengeluaran/index'
import { Route as KeuanganPembayaranNonSppIndexImport } from './pages/keuangan/pembayaran-non-spp/index'
import { Route as KeuanganPemasukanIndexImport } from './pages/keuangan/pemasukan/index'
import { Route as AkademikJadwalPengajarIndexImport } from './pages/akademik/jadwal-pengajar/index'
import { Route as AkademikJadwalPelajaranIndexImport } from './pages/akademik/jadwal-pelajaran/index'
import { Route as AkademikAbsensiPertemuanIndexImport } from './pages/akademik/absensi-pertemuan/index'
import { Route as AbsensiRecapIndexImport } from './pages/absensi/recap/index'
import { Route as AbsensiPengaturanIndexImport } from './pages/absensi/pengaturan/index'
import { Route as AbsensiLiburIndexImport } from './pages/absensi/libur/index'
import { Route as AbsensiJadwalIndexImport } from './pages/absensi/jadwal/index'
import { Route as AbsensiabsensiIndexImport } from './pages/absensi/(absensi)/index'
import { Route as AkademikJadwalPelajaranJadwalPelajaranDetailImport } from './pages/akademik/jadwal-pelajaran/jadwal-pelajaran-detail'
import { Route as AkademikAbsensiPertemuanAbsensiPertemuanDetailImport } from './pages/akademik/absensi-pertemuan/absensi-pertemuan-detail'
import { Route as PenggajianReferensiTunjanganIndexImport } from './pages/penggajian/referensi/tunjangan/index'
import { Route as PenggajianReferensiPotonganIndexImport } from './pages/penggajian/referensi/potongan/index'
import { Route as PenggajianReferensiHonorStaffIndexImport } from './pages/penggajian/referensi/honor-staff/index'
import { Route as PenggajianReferensiHonorGuruIndexImport } from './pages/penggajian/referensi/honor-guru/index'
import { Route as KeuanganSppTagihanIndexImport } from './pages/keuangan/spp/tagihan/index'
import { Route as KeuanganSppDataSppIndexImport } from './pages/keuangan/spp/data-spp/index'
import { Route as KeuanganReferensiSaldoKasIndexImport } from './pages/keuangan/referensi/saldo-kas/index'
import { Route as KeuanganReferensiKategoriPengeluaranIndexImport } from './pages/keuangan/referensi/kategori-pengeluaran/index'
import { Route as KeuanganReferensiKategoriPendapatanIndexImport } from './pages/keuangan/referensi/kategori-pendapatan/index'
import { Route as AkademikReferensiTahunAjaranIndexImport } from './pages/akademik/referensi/tahun-ajaran/index'
import { Route as AkademikReferensiMataPelajaranIndexImport } from './pages/akademik/referensi/mata-pelajaran/index'
import { Route as AkademikReferensiKelasIndexImport } from './pages/akademik/referensi/kelas/index'
import { Route as AbsensiIzinIzinStaffIndexImport } from './pages/absensi/izin/izin-staff/index'
import { Route as AbsensiIzinIzinSiswaIndexImport } from './pages/absensi/izin/izin-siswa/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StaffIndexRoute = StaffIndexImport.update({
  path: '/staff/',
  getParentRoute: () => rootRoute,
} as any)

const SiswaIndexRoute = SiswaIndexImport.update({
  path: '/siswa/',
  getParentRoute: () => rootRoute,
} as any)

const SekolahIndexRoute = SekolahIndexImport.update({
  path: '/sekolah/',
  getParentRoute: () => rootRoute,
} as any)

const PsbIndexRoute = PsbIndexImport.update({
  path: '/psb/',
  getParentRoute: () => rootRoute,
} as any)

const PortalIndexRoute = PortalIndexImport.update({
  path: '/portal/',
  getParentRoute: () => rootRoute,
} as any)

const InformasiIndexRoute = InformasiIndexImport.update({
  path: '/informasi/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const CbtIndexRoute = CbtIndexImport.update({
  path: '/cbt/',
  getParentRoute: () => rootRoute,
} as any)

const AkademikIndexRoute = AkademikIndexImport.update({
  path: '/akademik/',
  getParentRoute: () => rootRoute,
} as any)

const AgendaIndexRoute = AgendaIndexImport.update({
  path: '/agenda/',
  getParentRoute: () => rootRoute,
} as any)

const StaffStaffEditRoute = StaffStaffEditImport.update({
  path: '/staff/staff-edit',
  getParentRoute: () => rootRoute,
} as any)

const StaffStaffCreateRoute = StaffStaffCreateImport.update({
  path: '/staff/staff-create',
  getParentRoute: () => rootRoute,
} as any)

const SiswaSiswaDetailRoute = SiswaSiswaDetailImport.update({
  path: '/siswa/siswa-detail',
  getParentRoute: () => rootRoute,
} as any)

const PsbPsbDetailRoute = PsbPsbDetailImport.update({
  path: '/psb/psb-detail',
  getParentRoute: () => rootRoute,
} as any)

const CbtCbtSoalFormRoute = CbtCbtSoalFormImport.update({
  path: '/cbt/cbt-soal-form',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const PenggunaProfilIndexRoute = PenggunaProfilIndexImport.update({
  path: '/pengguna/profil/',
  getParentRoute: () => rootRoute,
} as any)

const PenggunapenggunaIndexRoute = PenggunapenggunaIndexImport.update({
  path: '/pengguna/',
  getParentRoute: () => rootRoute,
} as any)

const PenggajianProfilGajiStaffIndexRoute =
  PenggajianProfilGajiStaffIndexImport.update({
    path: '/penggajian/profil-gaji-staff/',
    getParentRoute: () => rootRoute,
  } as any)

const PenggajianProfilGajiGuruIndexRoute =
  PenggajianProfilGajiGuruIndexImport.update({
    path: '/penggajian/profil-gaji-guru/',
    getParentRoute: () => rootRoute,
  } as any)

const PenggajianpenggajianIndexRoute = PenggajianpenggajianIndexImport.update({
  path: '/penggajian/',
  getParentRoute: () => rootRoute,
} as any)

const PelanggaranPointPelanggaranIndexRoute =
  PelanggaranPointPelanggaranIndexImport.update({
    path: '/pelanggaran/point-pelanggaran/',
    getParentRoute: () => rootRoute,
  } as any)

const PelanggaranPelanggaranSiswaIndexRoute =
  PelanggaranPelanggaranSiswaIndexImport.update({
    path: '/pelanggaran/pelanggaran-siswa/',
    getParentRoute: () => rootRoute,
  } as any)

const PelanggaranJenisPelanggaranIndexRoute =
  PelanggaranJenisPelanggaranIndexImport.update({
    path: '/pelanggaran/jenis-pelanggaran/',
    getParentRoute: () => rootRoute,
  } as any)

const KeuanganRekapitulasiIndexRoute = KeuanganRekapitulasiIndexImport.update({
  path: '/keuangan/rekapitulasi/',
  getParentRoute: () => rootRoute,
} as any)

const KeuanganPengeluaranIndexRoute = KeuanganPengeluaranIndexImport.update({
  path: '/keuangan/pengeluaran/',
  getParentRoute: () => rootRoute,
} as any)

const KeuanganPembayaranNonSppIndexRoute =
  KeuanganPembayaranNonSppIndexImport.update({
    path: '/keuangan/pembayaran-non-spp/',
    getParentRoute: () => rootRoute,
  } as any)

const KeuanganPemasukanIndexRoute = KeuanganPemasukanIndexImport.update({
  path: '/keuangan/pemasukan/',
  getParentRoute: () => rootRoute,
} as any)

const AkademikJadwalPengajarIndexRoute =
  AkademikJadwalPengajarIndexImport.update({
    path: '/akademik/jadwal-pengajar/',
    getParentRoute: () => rootRoute,
  } as any)

const AkademikJadwalPelajaranIndexRoute =
  AkademikJadwalPelajaranIndexImport.update({
    path: '/akademik/jadwal-pelajaran/',
    getParentRoute: () => rootRoute,
  } as any)

const AkademikAbsensiPertemuanIndexRoute =
  AkademikAbsensiPertemuanIndexImport.update({
    path: '/akademik/absensi-pertemuan/',
    getParentRoute: () => rootRoute,
  } as any)

const AbsensiRecapIndexRoute = AbsensiRecapIndexImport.update({
  path: '/absensi/recap/',
  getParentRoute: () => rootRoute,
} as any)

const AbsensiPengaturanIndexRoute = AbsensiPengaturanIndexImport.update({
  path: '/absensi/pengaturan/',
  getParentRoute: () => rootRoute,
} as any)

const AbsensiLiburIndexRoute = AbsensiLiburIndexImport.update({
  path: '/absensi/libur/',
  getParentRoute: () => rootRoute,
} as any)

const AbsensiJadwalIndexRoute = AbsensiJadwalIndexImport.update({
  path: '/absensi/jadwal/',
  getParentRoute: () => rootRoute,
} as any)

const AbsensiabsensiIndexRoute = AbsensiabsensiIndexImport.update({
  path: '/absensi/',
  getParentRoute: () => rootRoute,
} as any)

const AkademikJadwalPelajaranJadwalPelajaranDetailRoute =
  AkademikJadwalPelajaranJadwalPelajaranDetailImport.update({
    path: '/akademik/jadwal-pelajaran/jadwal-pelajaran-detail',
    getParentRoute: () => rootRoute,
  } as any)

const AkademikAbsensiPertemuanAbsensiPertemuanDetailRoute =
  AkademikAbsensiPertemuanAbsensiPertemuanDetailImport.update({
    path: '/akademik/absensi-pertemuan/absensi-pertemuan-detail',
    getParentRoute: () => rootRoute,
  } as any)

const PenggajianReferensiTunjanganIndexRoute =
  PenggajianReferensiTunjanganIndexImport.update({
    path: '/penggajian/referensi/tunjangan/',
    getParentRoute: () => rootRoute,
  } as any)

const PenggajianReferensiPotonganIndexRoute =
  PenggajianReferensiPotonganIndexImport.update({
    path: '/penggajian/referensi/potongan/',
    getParentRoute: () => rootRoute,
  } as any)

const PenggajianReferensiHonorStaffIndexRoute =
  PenggajianReferensiHonorStaffIndexImport.update({
    path: '/penggajian/referensi/honor-staff/',
    getParentRoute: () => rootRoute,
  } as any)

const PenggajianReferensiHonorGuruIndexRoute =
  PenggajianReferensiHonorGuruIndexImport.update({
    path: '/penggajian/referensi/honor-guru/',
    getParentRoute: () => rootRoute,
  } as any)

const KeuanganSppTagihanIndexRoute = KeuanganSppTagihanIndexImport.update({
  path: '/keuangan/spp/tagihan/',
  getParentRoute: () => rootRoute,
} as any)

const KeuanganSppDataSppIndexRoute = KeuanganSppDataSppIndexImport.update({
  path: '/keuangan/spp/data-spp/',
  getParentRoute: () => rootRoute,
} as any)

const KeuanganReferensiSaldoKasIndexRoute =
  KeuanganReferensiSaldoKasIndexImport.update({
    path: '/keuangan/referensi/saldo-kas/',
    getParentRoute: () => rootRoute,
  } as any)

const KeuanganReferensiKategoriPengeluaranIndexRoute =
  KeuanganReferensiKategoriPengeluaranIndexImport.update({
    path: '/keuangan/referensi/kategori-pengeluaran/',
    getParentRoute: () => rootRoute,
  } as any)

const KeuanganReferensiKategoriPendapatanIndexRoute =
  KeuanganReferensiKategoriPendapatanIndexImport.update({
    path: '/keuangan/referensi/kategori-pendapatan/',
    getParentRoute: () => rootRoute,
  } as any)

const AkademikReferensiTahunAjaranIndexRoute =
  AkademikReferensiTahunAjaranIndexImport.update({
    path: '/akademik/referensi/tahun-ajaran/',
    getParentRoute: () => rootRoute,
  } as any)

const AkademikReferensiMataPelajaranIndexRoute =
  AkademikReferensiMataPelajaranIndexImport.update({
    path: '/akademik/referensi/mata-pelajaran/',
    getParentRoute: () => rootRoute,
  } as any)

const AkademikReferensiKelasIndexRoute =
  AkademikReferensiKelasIndexImport.update({
    path: '/akademik/referensi/kelas/',
    getParentRoute: () => rootRoute,
  } as any)

const AbsensiIzinIzinStaffIndexRoute = AbsensiIzinIzinStaffIndexImport.update({
  path: '/absensi/izin/izin-staff/',
  getParentRoute: () => rootRoute,
} as any)

const AbsensiIzinIzinSiswaIndexRoute = AbsensiIzinIzinSiswaIndexImport.update({
  path: '/absensi/izin/izin-siswa/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/cbt/cbt-soal-form': {
      preLoaderRoute: typeof CbtCbtSoalFormImport
      parentRoute: typeof rootRoute
    }
    '/psb/psb-detail': {
      preLoaderRoute: typeof PsbPsbDetailImport
      parentRoute: typeof rootRoute
    }
    '/siswa/siswa-detail': {
      preLoaderRoute: typeof SiswaSiswaDetailImport
      parentRoute: typeof rootRoute
    }
    '/staff/staff-create': {
      preLoaderRoute: typeof StaffStaffCreateImport
      parentRoute: typeof rootRoute
    }
    '/staff/staff-edit': {
      preLoaderRoute: typeof StaffStaffEditImport
      parentRoute: typeof rootRoute
    }
    '/agenda/': {
      preLoaderRoute: typeof AgendaIndexImport
      parentRoute: typeof rootRoute
    }
    '/akademik/': {
      preLoaderRoute: typeof AkademikIndexImport
      parentRoute: typeof rootRoute
    }
    '/cbt/': {
      preLoaderRoute: typeof CbtIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/informasi/': {
      preLoaderRoute: typeof InformasiIndexImport
      parentRoute: typeof rootRoute
    }
    '/portal/': {
      preLoaderRoute: typeof PortalIndexImport
      parentRoute: typeof rootRoute
    }
    '/psb/': {
      preLoaderRoute: typeof PsbIndexImport
      parentRoute: typeof rootRoute
    }
    '/sekolah/': {
      preLoaderRoute: typeof SekolahIndexImport
      parentRoute: typeof rootRoute
    }
    '/siswa/': {
      preLoaderRoute: typeof SiswaIndexImport
      parentRoute: typeof rootRoute
    }
    '/staff/': {
      preLoaderRoute: typeof StaffIndexImport
      parentRoute: typeof rootRoute
    }
    '/akademik/absensi-pertemuan/absensi-pertemuan-detail': {
      preLoaderRoute: typeof AkademikAbsensiPertemuanAbsensiPertemuanDetailImport
      parentRoute: typeof rootRoute
    }
    '/akademik/jadwal-pelajaran/jadwal-pelajaran-detail': {
      preLoaderRoute: typeof AkademikJadwalPelajaranJadwalPelajaranDetailImport
      parentRoute: typeof rootRoute
    }
    '/absensi/(absensi)/': {
      preLoaderRoute: typeof AbsensiabsensiIndexImport
      parentRoute: typeof rootRoute
    }
    '/absensi/jadwal/': {
      preLoaderRoute: typeof AbsensiJadwalIndexImport
      parentRoute: typeof rootRoute
    }
    '/absensi/libur/': {
      preLoaderRoute: typeof AbsensiLiburIndexImport
      parentRoute: typeof rootRoute
    }
    '/absensi/pengaturan/': {
      preLoaderRoute: typeof AbsensiPengaturanIndexImport
      parentRoute: typeof rootRoute
    }
    '/absensi/recap/': {
      preLoaderRoute: typeof AbsensiRecapIndexImport
      parentRoute: typeof rootRoute
    }
    '/akademik/absensi-pertemuan/': {
      preLoaderRoute: typeof AkademikAbsensiPertemuanIndexImport
      parentRoute: typeof rootRoute
    }
    '/akademik/jadwal-pelajaran/': {
      preLoaderRoute: typeof AkademikJadwalPelajaranIndexImport
      parentRoute: typeof rootRoute
    }
    '/akademik/jadwal-pengajar/': {
      preLoaderRoute: typeof AkademikJadwalPengajarIndexImport
      parentRoute: typeof rootRoute
    }
    '/keuangan/pemasukan/': {
      preLoaderRoute: typeof KeuanganPemasukanIndexImport
      parentRoute: typeof rootRoute
    }
    '/keuangan/pembayaran-non-spp/': {
      preLoaderRoute: typeof KeuanganPembayaranNonSppIndexImport
      parentRoute: typeof rootRoute
    }
    '/keuangan/pengeluaran/': {
      preLoaderRoute: typeof KeuanganPengeluaranIndexImport
      parentRoute: typeof rootRoute
    }
    '/keuangan/rekapitulasi/': {
      preLoaderRoute: typeof KeuanganRekapitulasiIndexImport
      parentRoute: typeof rootRoute
    }
    '/pelanggaran/jenis-pelanggaran/': {
      preLoaderRoute: typeof PelanggaranJenisPelanggaranIndexImport
      parentRoute: typeof rootRoute
    }
    '/pelanggaran/pelanggaran-siswa/': {
      preLoaderRoute: typeof PelanggaranPelanggaranSiswaIndexImport
      parentRoute: typeof rootRoute
    }
    '/pelanggaran/point-pelanggaran/': {
      preLoaderRoute: typeof PelanggaranPointPelanggaranIndexImport
      parentRoute: typeof rootRoute
    }
    '/penggajian/(penggajian)/': {
      preLoaderRoute: typeof PenggajianpenggajianIndexImport
      parentRoute: typeof rootRoute
    }
    '/penggajian/profil-gaji-guru/': {
      preLoaderRoute: typeof PenggajianProfilGajiGuruIndexImport
      parentRoute: typeof rootRoute
    }
    '/penggajian/profil-gaji-staff/': {
      preLoaderRoute: typeof PenggajianProfilGajiStaffIndexImport
      parentRoute: typeof rootRoute
    }
    '/pengguna/(pengguna)/': {
      preLoaderRoute: typeof PenggunapenggunaIndexImport
      parentRoute: typeof rootRoute
    }
    '/pengguna/profil/': {
      preLoaderRoute: typeof PenggunaProfilIndexImport
      parentRoute: typeof rootRoute
    }
    '/absensi/izin/izin-siswa/': {
      preLoaderRoute: typeof AbsensiIzinIzinSiswaIndexImport
      parentRoute: typeof rootRoute
    }
    '/absensi/izin/izin-staff/': {
      preLoaderRoute: typeof AbsensiIzinIzinStaffIndexImport
      parentRoute: typeof rootRoute
    }
    '/akademik/referensi/kelas/': {
      preLoaderRoute: typeof AkademikReferensiKelasIndexImport
      parentRoute: typeof rootRoute
    }
    '/akademik/referensi/mata-pelajaran/': {
      preLoaderRoute: typeof AkademikReferensiMataPelajaranIndexImport
      parentRoute: typeof rootRoute
    }
    '/akademik/referensi/tahun-ajaran/': {
      preLoaderRoute: typeof AkademikReferensiTahunAjaranIndexImport
      parentRoute: typeof rootRoute
    }
    '/keuangan/referensi/kategori-pendapatan/': {
      preLoaderRoute: typeof KeuanganReferensiKategoriPendapatanIndexImport
      parentRoute: typeof rootRoute
    }
    '/keuangan/referensi/kategori-pengeluaran/': {
      preLoaderRoute: typeof KeuanganReferensiKategoriPengeluaranIndexImport
      parentRoute: typeof rootRoute
    }
    '/keuangan/referensi/saldo-kas/': {
      preLoaderRoute: typeof KeuanganReferensiSaldoKasIndexImport
      parentRoute: typeof rootRoute
    }
    '/keuangan/spp/data-spp/': {
      preLoaderRoute: typeof KeuanganSppDataSppIndexImport
      parentRoute: typeof rootRoute
    }
    '/keuangan/spp/tagihan/': {
      preLoaderRoute: typeof KeuanganSppTagihanIndexImport
      parentRoute: typeof rootRoute
    }
    '/penggajian/referensi/honor-guru/': {
      preLoaderRoute: typeof PenggajianReferensiHonorGuruIndexImport
      parentRoute: typeof rootRoute
    }
    '/penggajian/referensi/honor-staff/': {
      preLoaderRoute: typeof PenggajianReferensiHonorStaffIndexImport
      parentRoute: typeof rootRoute
    }
    '/penggajian/referensi/potongan/': {
      preLoaderRoute: typeof PenggajianReferensiPotonganIndexImport
      parentRoute: typeof rootRoute
    }
    '/penggajian/referensi/tunjangan/': {
      preLoaderRoute: typeof PenggajianReferensiTunjanganIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  authLoginRoute,
  CbtCbtSoalFormRoute,
  PsbPsbDetailRoute,
  SiswaSiswaDetailRoute,
  StaffStaffCreateRoute,
  StaffStaffEditRoute,
  AgendaIndexRoute,
  AkademikIndexRoute,
  CbtIndexRoute,
  DashboardIndexRoute,
  InformasiIndexRoute,
  PortalIndexRoute,
  PsbIndexRoute,
  SekolahIndexRoute,
  SiswaIndexRoute,
  StaffIndexRoute,
  AkademikAbsensiPertemuanAbsensiPertemuanDetailRoute,
  AkademikJadwalPelajaranJadwalPelajaranDetailRoute,
  AbsensiabsensiIndexRoute,
  AbsensiJadwalIndexRoute,
  AbsensiLiburIndexRoute,
  AbsensiPengaturanIndexRoute,
  AbsensiRecapIndexRoute,
  AkademikAbsensiPertemuanIndexRoute,
  AkademikJadwalPelajaranIndexRoute,
  AkademikJadwalPengajarIndexRoute,
  KeuanganPemasukanIndexRoute,
  KeuanganPembayaranNonSppIndexRoute,
  KeuanganPengeluaranIndexRoute,
  KeuanganRekapitulasiIndexRoute,
  PelanggaranJenisPelanggaranIndexRoute,
  PelanggaranPelanggaranSiswaIndexRoute,
  PelanggaranPointPelanggaranIndexRoute,
  PenggajianpenggajianIndexRoute,
  PenggajianProfilGajiGuruIndexRoute,
  PenggajianProfilGajiStaffIndexRoute,
  PenggunapenggunaIndexRoute,
  PenggunaProfilIndexRoute,
  AbsensiIzinIzinSiswaIndexRoute,
  AbsensiIzinIzinStaffIndexRoute,
  AkademikReferensiKelasIndexRoute,
  AkademikReferensiMataPelajaranIndexRoute,
  AkademikReferensiTahunAjaranIndexRoute,
  KeuanganReferensiKategoriPendapatanIndexRoute,
  KeuanganReferensiKategoriPengeluaranIndexRoute,
  KeuanganReferensiSaldoKasIndexRoute,
  KeuanganSppDataSppIndexRoute,
  KeuanganSppTagihanIndexRoute,
  PenggajianReferensiHonorGuruIndexRoute,
  PenggajianReferensiHonorStaffIndexRoute,
  PenggajianReferensiPotonganIndexRoute,
  PenggajianReferensiTunjanganIndexRoute,
])

/* prettier-ignore-end */
